// AUTO-GENERATED by design/build_tokens.py from design/palette.json —
// do not edit. Change the palette and re-run the generator.
//
// Hex (not HSL) because React Native's StyleSheet takes colour strings
// directly and gains nothing from a composable triple.

export type GeneratedColors = {
  background:             string;
  surface:                string;
  surfaceMuted:           string;
  surfaceElevated:        string;
  card:                   string;
  foreground:             string;
  mutedForeground:        string;
  subtleForeground:       string;
  brandText:              string;
  primary:                string;
  primaryForeground:      string;
  primaryLight:           string;
  primaryStrong:          string;
  accent:                 string;
  accentForeground:       string;
  brandSurface:           string;
  brandSurfaceForeground: string;
  brand:                  string;
  brandForeground:        string;
  brandLight:             string;
  brandOutdoor:           string;
  gold:                   string;
  goldLight:              string;
  success:                string;
  successLight:           string;
  warning:                string;
  warningLight:           string;
  danger:                 string;
  dangerLight:            string;
  info:                   string;
  infoLight:              string;
  driver:                 string;
  driverLight:            string;
  walker:                 string;
  walkerLight:            string;
  trainer:                string;
  trainerLight:           string;
  trainee:                string;
  traineeLight:           string;
  neutral:                string;
  neutralLight:           string;
  border:                 string;
  borderStrong:           string;
  swatchRing:             string;
  ring:                   string;
  tabBar:                 string;
  tabBarBorder:           string;
  skeleton:               string;
  skeletonShimmer:        string;
};

export const generatedLight: GeneratedColors = {
  background:             '#F9F9FB',
  surface:                '#FFFFFF',
  surfaceMuted:           '#F3F4F7',
  surfaceElevated:        '#FFFFFF',
  card:                   '#FFFFFF',
  foreground:             '#111522',
  mutedForeground:        '#656C7B',
  subtleForeground:       '#575D6B',
  brandText:              '#8517D3',
  primary:                '#1B296A',
  primaryForeground:      '#FFFFFF',
  primaryLight:           '#EBEDFA',
  primaryStrong:          '#121C49',
  accent:                 '#F0F0FF',
  accentForeground:       '#2046B6',
  brandSurface:           '#16235A',
  brandSurfaceForeground: '#FFFFFF',
  brand:                  '#8517D3',
  brandForeground:        '#FFFFFF',
  brandLight:             '#F6EDFD',
  brandOutdoor:           '#740FBD',
  gold:                   '#A35F00',
  goldLight:              '#FFF4E5',
  success:                '#066B4C',
  successLight:           '#E5FAF4',
  warning:                '#A94104',
  warningLight:           '#FDECE2',
  danger:                 '#BB251B',
  dangerLight:            '#FCE9E8',
  info:                   '#0C5D97',
  infoLight:              '#E3F2FC',
  driver:                 '#0C5D97',
  driverLight:            '#E3F2FC',
  walker:                 '#066B4C',
  walkerLight:            '#E5FAF4',
  trainer:                '#A35F00',
  trainerLight:           '#FFF4E5',
  trainee:                '#8517D3',
  traineeLight:           '#F6EDFD',
  neutral:                '#656C7B',
  neutralLight:           '#F3F4F7',
  border:                 '#DCDFE5',
  borderStrong:           '#B9BFCA',
  swatchRing:             '#737B8C',
  ring:                   '#1795A1',
  tabBar:                 '#FFFFFF',
  tabBarBorder:           '#DCDFE5',
  skeleton:               '#EAECF1',
  skeletonShimmer:        '#F6F7F9',
};

export const generatedDark: GeneratedColors = {
  background:             '#0E132F',
  surface:                '#181D39',
  surfaceMuted:           '#232843',
  surfaceElevated:        '#1C223F',
  card:                   '#181D39',
  foreground:             '#F2F5F7',
  mutedForeground:        '#ABB2BF',
  subtleForeground:       '#8D95A5',
  brandText:              '#B475EB',
  primary:                '#7E95F1',
  primaryForeground:      '#0B1028',
  primaryLight:           '#1F2951',
  primaryStrong:          '#A1B2F7',
  accent:                 '#1E263E',
  accentForeground:       '#8CA6F2',
  brandSurface:           '#16235A',
  brandSurfaceForeground: '#FFFFFF',
  brand:                  '#A55AE7',
  brandForeground:        '#0B1028',
  brandLight:             '#3F2556',
  brandOutdoor:           '#CA97F7',
  gold:                   '#F5A524',
  goldLight:              '#594422',
  success:                '#59CFAB',
  successLight:           '#244C40',
  warning:                '#F7803B',
  warningLight:           '#593622',
  danger:                 '#EB6960',
  dangerLight:            '#5D2B28',
  info:                   '#4CACF0',
  infoLight:              '#254156',
  driver:                 '#4CACF0',
  driverLight:            '#254156',
  walker:                 '#59CFAB',
  walkerLight:            '#244C40',
  trainer:                '#F5A524',
  trainerLight:           '#594422',
  trainee:                '#A55AE7',
  traineeLight:           '#3F2556',
  neutral:                '#ABB2BF',
  neutralLight:           '#232843',
  border:                 '#323753',
  borderStrong:           '#4E5374',
  swatchRing:             '#737B8C',
  ring:                   '#94E0F9',
  tabBar:                 '#151A32',
  tabBarBorder:           '#323753',
  skeleton:               '#272C49',
  skeletonShimmer:        '#32385D',
};


/**
 * Continuous urgency ramp. NOT semantic tokens — these are anchors that
 * get interpolated between, which single-value success/warning/danger
 * cannot express. Theme-constant on purpose: the ramp encodes time
 * pressure, and it must mean the same thing in either theme.
 */
export const ramp = {
  urgencyNone:        '#3B82F6',
  urgencyFarDeep:     '#10B981',
  urgencyFarPale:     '#34D399',
  urgencyCautionPale: '#FBB830',
  urgencyCautionDeep: '#F97316',
  urgencyUrgent:      '#EF4444',
  urgencyClosed:      '#450A0A',
} as const;
