# ---------------------------------------------------------------------------
# Role constants — single source of truth for all employee role strings.
# Import these instead of scattering bare string literals across routers.
# ---------------------------------------------------------------------------

# Field-operational roles that appear on daily dispatch assignments
FIELD_ROLES: tuple[str, ...] = ("driver", "trainer", "trainee", "walker")

# Back-office roles that manage or administer the platform
MANAGEMENT_ROLES: tuple[str, ...] = ("management", "admin")

# Privileged staff who can see/manage other employees' data
OVERSIGHT_ROLES: tuple[str, ...] = ("management", "admin", "dispatch")

# Roles that receive dispatch assignments (appear in assigned_crews)
ASSIGNABLE_ROLES: tuple[str, ...] = ("driver", "trainer", "trainee", "walker")

# Shortcuts for individual roles
ROLE_DRIVER    = "driver"
ROLE_TRAINER   = "trainer"
ROLE_TRAINEE   = "trainee"
ROLE_WALKER    = "walker"
ROLE_DISPATCH  = "dispatch"
ROLE_MANAGEMENT = "management"
ROLE_ADMIN     = "admin"

# ---------------------------------------------------------------------------

ROLE_BOOST = {
    "driver": 0.70,
    "trainer": 0.50,
    "walker": 0.30
}

MUTUAL_BONUS = {
    "bidirectional": 0.10,
    "tridirectional": 0.20
}

CONSECUTIVE_PENALTY = 0.05
CAP = 0.85

MIN_WALKERS_PER_TRUCK = 3

# Number of dispatch days a mandatory task can be carried as debt before the
# TrainingRecord is flagged for manager escalation.
DEBT_ESCALATION_THRESHOLD = 3

# Maximum curriculum phase number. Phase 4 is practical shadowing (observation).
# Phase 5 is remediation-only, generated by score_phase4 on fail — never injected.
MAX_TRAINING_PHASE = 4