"""Every notification type's severity, channels, label and tone (ADR-487 D1).

ONE TABLE, BECAUSE THE ALTERNATIVE WAS FOUR
===========================================

Before this, routing a notification was decided in four independent places and
none of them was complete:

    backend literals        61 types   what actually exists
    TYPE_META (mobile)      48 types   label + icon
    typeColor (mobile)      18 exact + 5 substring rules
    styleForType (web)       4 exact + 4 pattern rules

31 backend types had no mobile label — including every urgent one. The web's
pattern rules gave `incident_critical_injury` a warning treatment only because
somebody happened to put the word "critical" in the name; rename it and an injury
alert silently becomes a plain grey card. Measured across the corpus, 30 of 61
type names matched no naming convention at all.

TWO INDEPENDENT AXES
====================

The channel set says WHERE a notification goes. Severity governs only QUIET
HOURS. They are not derived from each other, and the registry proves why:

    dispatch_finalized              INFO    pushes      (the crew's need-to-know)
    manifest_enrichment             INFO    no push     (a background job)
    dispatch_finalization_reminder  ACTION  no push     (fires on a timer)

So INFO does not mean "quiet" — it means "nothing is waiting on you", and plenty
of things nobody must answer still have to arrive.

WHY A TONE AND NOT A COLOUR
===========================

Mobile's palette is generated by `design/build_tokens.py` and contrast-checked in
CI; the web's comes from Tailwind CSS variables. They are independently generated
and independently verified, so a hex value from this file would bypass both. The
server says what a message MEANS and each client maps that to its own token.

AN UNDECLARED TYPE RAISES. IT DOES NOT DEFAULT.
===============================================

`resolve_spec` refuses rather than falling back to INFO, because a default of INFO
is exactly today's behaviour — a lenient lookup would make this file decorative
and pass silently in the one case it exists to catch. See ADR-487 D1.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Flag, StrEnum, auto


class Severity(StrEnum):
    """What it costs to miss this. Governs quiet hours, nothing else."""

    URGENT = "urgent"   # somebody is hurt, or the operation is stopping
    ACTION = "action"   # waiting on THIS person's response
    NOTICE = "notice"   # tenant-authored or platform-seeded, fires because a time arrived
    INFO = "info"       # a system or third-party event; nobody is blocked


class Channel(Flag):
    """Where it goes. INBOX is unconditional and therefore absent.

    Every notification is a row whatever else happens to it, so a channel set of
    TICKER means "ticker and the archive", never "ticker instead of a record".
    """

    NONE = 0
    BANNER = auto()     # web banner / mobile Today card (ADR-275)
    TICKER = auto()     # the scrolling strip (D4b)
    PUSH = auto()       # APNs / FCM via SNS (D5)
    DISCORD = auto()    # secondary surface, never the channel of record (ADR-324)
    GATE = auto()       # root-navigator swap; cannot be worked around (D8)
    PROMPT = auto()     # escapable modal, once per launch (D8)


class Tone(StrEnum):
    """The semantic colour role. NOT a hex value and NOT a token name."""

    NEUTRAL = "neutral"
    GOOD = "good"
    WARN = "warn"
    BAD = "bad"
    ACTIVE = "active"


@dataclass(frozen=True)
class Spec:
    severity: Severity
    channels: Channel
    label: str          # the short noun phrase a human reads
    tone: Tone
    icon: str           # one emoji; mobile renders it, web maps it to a glyph


class UndeclaredNotificationType(RuntimeError):
    """Raised by resolve_spec for a type with no entry. Never caught to default."""


# Module-level aliases so the table below reads as a table.
URGENT, ACTION, NOTICE, INFO = (
    Severity.URGENT, Severity.ACTION, Severity.NOTICE, Severity.INFO)
BANNER, TICKER, PUSH, DISCORD, GATE, PROMPT = (
    Channel.BANNER, Channel.TICKER, Channel.PUSH, Channel.DISCORD,
    Channel.GATE, Channel.PROMPT)
NEUTRAL, GOOD, WARN, BAD, ACTIVE = (
    Tone.NEUTRAL, Tone.GOOD, Tone.WARN, Tone.BAD, Tone.ACTIVE)


SPEC: dict[str, Spec] = {

    # ── URGENT ────────────────────────────────────────────────────────────
    "driver_help_requested": Spec(URGENT, BANNER | PUSH | DISCORD,
        'Driver Needs Help', BAD, '🆘'),   # Oversight
    "incident_critical": Spec(URGENT, BANNER | PUSH | DISCORD,
        'Critical Incident', BAD, '🚨'),   # Oversight
    "rebalance_intervention_required": Spec(URGENT, BANNER | PUSH | DISCORD,
        'Needs Dispatch', BAD, '⚠️'),   # Oversight
    "trainee_help_request": Spec(URGENT, BANNER | PUSH | DISCORD,
        'Help Needed', BAD, '🆘'),   # Oversight

    # ── ACTION ────────────────────────────────────────────────────────────
    "assignment_change_request": Spec(ACTION, BANNER,
        'Reassign Request', ACTIVE, '📨'),   # Dispatch
    "captain_declined": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Captain Declined', WARN, '🔀'),   # Oversight
    "continuation_request": Spec(ACTION, BANNER,
        'Continuation Request', ACTIVE, '📨'),   # The trainer
    "dispatch_assignment": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Assignment', ACTIVE, '📋'),   # The assignee
    "dispatch_finalization_reminder": Spec(ACTION, BANNER,
        'Finalize Dispatch', WARN, '⏰'),   # Dispatch + admin
    "dispatch_no_captain": Spec(ACTION, BANNER | PUSH | DISCORD,
        'No Captain', WARN, '⚠️'),   # Oversight
    "driver_trainee_declined": Spec(ACTION, BANNER,
        'Driver Declined', WARN, '🔀'),   # Oversight
    "driver_trainee_supervisor_declined": Spec(ACTION, BANNER,
        'Supervisor Declined', WARN, '🔀'),   # Oversight
    "email_bounced": Spec(ACTION, BANNER,
        'Email Bounced', WARN, '📧'),   # Management + admin
    "fuel_log_reminder": Spec(ACTION, BANNER,
        'Fuel Log Due', ACTIVE, '⛽'),   # The driver
    "inspection_failed": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Inspection Failed', BAD, '🔧'),   # Oversight + the driver
    "quiz_issued": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Quiz Ready', ACTIVE, '📝'),   # The trainee
    "quiz_remediation_scheduled": Spec(ACTION, BANNER,
        'Remediation Set', ACTIVE, '📝'),   # Management + admin
    "quiz_unsubmitted_reminder": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Quiz Due', WARN, '📝'),   # The paired trainer
    "schedule_change_request": Spec(ACTION, BANNER,
        'Schedule Request', ACTIVE, '📨'),   # The reviewer (mgmt/admin)
    "sort_packages_dropped": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Packages Dropped', BAD, '⚠️'),   # Oversight
    "timecard_disputed": Spec(ACTION, BANNER,
        'Timecard Disputed', WARN, '🕐'),   # Admin + management
    "timecard_mismatch": Spec(ACTION, BANNER | GATE,
        'Timecard Mismatch', WARN, '🕐'),   # Admin + management
    "timecard_pending_manager": Spec(ACTION, BANNER,
        'Timecard To Approve', ACTIVE, '🕐'),   # Admin + management
    "timecard_update_failed": Spec(ACTION, BANNER,
        'Timecard Failed', BAD, '🕐'),   # Admin + management
    "trainee_decline": Spec(ACTION, BANNER,
        'Trainee Declined', WARN, '🔀'),   # Oversight
    "trainee_left_early": Spec(ACTION, BANNER,
        'Left Early', WARN, '⚠️'),   # Oversight
    "trainee_reassign_warning": Spec(ACTION, BANNER,
        'Reassign Warning', WARN, '⚠️'),   # Oversight
    "trainer_decline_reassignment": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Reassignment', WARN, '🔀'),   # Oversight + the trainee
    "training_record_due": Spec(ACTION, BANNER | PUSH | DISCORD,
        'Record Due', WARN, '📋'),   # The assigned trainer
    "training_record_unsubmitted": Spec(ACTION, BANNER,
        'Record Due', WARN, '📋'),   # Management + admin

    # ── INFO ──────────────────────────────────────────────────────────────
    "anchor_point_arrived": Spec(INFO, TICKER | PUSH | DISCORD,
        'AP Arrival', GOOD, '📍'),   # The crew
    "anchor_point_departed": Spec(INFO, TICKER | PUSH | DISCORD,
        'AP Departure', NEUTRAL, '📍'),   # The crew
    "anchor_point_running_late": Spec(INFO, BANNER | PUSH | DISCORD,
        'Driver Running Late', WARN, '⏰'),   # The crew
    "anchor_point_submitted": Spec(INFO, TICKER | PUSH | DISCORD,
        'AP Posted', NEUTRAL, '📍'),   # The crew
    "assignment_change_approved": Spec(INFO, BANNER,
        'Reassign Approved', GOOD, '✅'),   # The requester
    "assignment_change_rejected": Spec(INFO, BANNER,
        'Reassign Denied', BAD, '❌'),   # The requester
    "ban_override_reassignment": Spec(INFO, BANNER,
        'Override Notice', WARN, '🔀'),   # Oversight
    "campaign_schedule_ended": Spec(INFO, BANNER,
        'Campaign Ended', NEUTRAL, '📋'),   # Management + admin
    "credentials_sent": Spec(INFO, BANNER | PUSH | DISCORD | GATE,
        'Credentials', NEUTRAL, '🔑'),   # The trainee
    "crew_all_confirmed": Spec(INFO, TICKER,
        'Crew Confirmed', GOOD, '✅'),   # Oversight
    "crew_roster_submitted": Spec(INFO, TICKER,
        'Roster In', NEUTRAL, '📋'),   # Oversight
    "dispatch_assignment_info": Spec(INFO, BANNER,
        'Assignment Update', ACTIVE, '📋'),   # The assignee
    "dispatch_finalized": Spec(INFO, TICKER | PUSH | DISCORD,
        'Dispatch Final', GOOD, '✅'),   # The crew
    "employee_offboarding": Spec(INFO, BANNER,
        'Offboarding', WARN, '👤'),   # Admin + manager
    "exemplary_trainer": Spec(INFO, TICKER,
        'Trainer Noted', GOOD, '⭐'),   # Management
    "feedback_submitted": Spec(INFO, TICKER,
        'Feedback', NEUTRAL, '💬'),   # Admins
    "graduation": Spec(INFO, BANNER | PUSH | DISCORD | GATE,
        'Graduation', GOOD, '🎓'),   # The trainee who graduated
    "incident_info": Spec(INFO, TICKER,
        'Incident', NEUTRAL, '📄'),   # Oversight
    "incident_resolved": Spec(INFO, TICKER,
        'Incident Resolved', GOOD, '✅'),   # The reporter
    "incident_submitted": Spec(INFO, BANNER,
        'Incident Filed', WARN, '📄'),   # The reporter (their own receipt)
    "incident_warning": Spec(INFO, BANNER,
        'Incident Warning', WARN, '⚠️'),   # Oversight
    "load_confirmed": Spec(INFO, TICKER,
        'Load Confirmed', GOOD, '🚚'),   # Oversight
    "manifest_enrichment": Spec(INFO, TICKER,
        'Manifest Updated', NEUTRAL, '📦'),   # Oversight
    "offday_approved": Spec(INFO, BANNER | PUSH | DISCORD,
        'Day Off Approved', GOOD, '✅'),   # The requester
    "offday_rejected": Spec(INFO, BANNER | PUSH | DISCORD,
        'Day Off Denied', BAD, '❌'),   # The requester
    "operating_mode_change": Spec(INFO, BANNER | GATE,
        'Mode Change', WARN, '⚙️'),   # Admin + management
    "phase4_failed": Spec(INFO, BANNER,
        'Phase 4 Result', BAD, '📊'),   # Management + the trainee
    "pto_approved": Spec(INFO, BANNER | PUSH | DISCORD,
        'PTO Approved', GOOD, '✅'),   # The requester
    "pto_rejected": Spec(INFO, BANNER | PUSH | DISCORD,
        'PTO Denied', BAD, '❌'),   # The requester
    "quiz_result_confirmed": Spec(INFO, BANNER,
        'Quiz Result', NEUTRAL, '📝'),   # The trainee
    "quiz_submitted": Spec(INFO, TICKER,
        'Quiz Submitted', NEUTRAL, '📝'),   # Management + admin
    "quiz_submitted_trainer": Spec(INFO, TICKER,
        'Quiz Submitted', NEUTRAL, '📝'),   # The paired trainer
    "role_change": Spec(INFO, BANNER,
        'Role Change', NEUTRAL, '👤'),   # The employee
    "route_ready": Spec(INFO, TICKER | PROMPT,
        'Your Route', ACTIVE, '🗺️'),   # The walker
    "rts_approved": Spec(INFO, BANNER,
        'RTS Approved', GOOD, '✅'),   # The driver
    "rts_rejected": Spec(INFO, BANNER,
        'RTS Rejected', BAD, '❌'),   # The driver
    "rts_submitted": Spec(INFO, TICKER,
        'RTS Submitted', NEUTRAL, '📦'),   # Oversight
    "schedule_change_approved": Spec(INFO, BANNER,
        'Schedule Approved', GOOD, '✅'),   # The requester
    "schedule_change_rejected": Spec(INFO, BANNER,
        'Schedule Denied', BAD, '❌'),   # The requester
    "timecard_applied": Spec(INFO, TICKER,
        'Timecard Applied', GOOD, '🕐'),   # The employee
    "timecard_rejected": Spec(INFO, BANNER,
        'Timecard Rejected', BAD, '🕐'),   # The employee
    "trainee_arrived": Spec(INFO, TICKER,
        'Trainee Arrived', GOOD, '✅'),   # The paired trainer
    "trainee_bumped": Spec(INFO, BANNER,
        'Trainee Bumped', WARN, '⚠️'),   # Oversight
    "trainee_graduated": Spec(INFO, BANNER,
        'Graduation', GOOD, '🎓'),   # Management
    "trainee_ncns": Spec(INFO, BANNER,
        'No Call No Show', WARN, '⚠️'),   # Oversight
    "trainee_reassigned": Spec(INFO, BANNER,
        'Reassigned', NEUTRAL, '🔀'),   # Oversight + the trainee
    "trainee_reset": Spec(INFO, BANNER,
        'Training Reset', WARN, '🔄'),   # Management
    "trainee_unassigned": Spec(INFO, BANNER,
        'Unassigned', WARN, '⚠️'),   # The trainee
    "training_phase_closed": Spec(INFO, BANNER,
        'Phase Complete', GOOD, '🎓'),   # The trainee
    "truck_transfer": Spec(INFO, TICKER | PUSH | DISCORD,
        'Truck Transfer', WARN, '🔀'),   # The person moved
    "underperforming_trainer": Spec(INFO, BANNER,
        'Trainer Alert', WARN, '⚠️'),   # Management
    "zone_sort_complete": Spec(INFO, TICKER,
        'Sort Complete', GOOD, '🗺️'),   # Oversight
}


# Retired: no longer raised, kept so reads of historical rows still resolve
# (ADR-487 D1 — removal is two-step, stop raising then mark retired).
RETIRED: dict[str, Spec] = {
    "incident_critical_injury": Spec(URGENT, BANNER | PUSH | DISCORD,
        "Critical Injury", BAD, "🚨"),      # duplicated incident_critical
    "schedule_change": Spec(INFO, BANNER,
        "Schedule Change", NEUTRAL, "📅"),   # covered by schedule_change_approved
    "schedule_change_denied": Spec(INFO, BANNER,
        "Schedule Denied", BAD, "❌"),       # covered by schedule_change_rejected
    "rts_revised": Spec(INFO, BANNER,
        "RTS Revised", WARN, "📦"),          # no revise-and-resubmit path exists
}


def resolve_spec(notification_type: str) -> Spec:
    """The ONLY lookup. An undeclared type is a hard failure, not a default.

    Refusing rather than defaulting is the decision (ADR-487 D1). A default of
    INFO is exactly the behaviour this registry replaces, so a lenient lookup
    would pass silently in the one case it exists to catch: an injury alert
    rendering as a grey card.

    Retired types resolve, so a notification raised months ago still reads. They
    are not raisable — `write_notification` rejects them separately.
    """
    try:
        return SPEC[notification_type]
    except KeyError:
        pass
    if notification_type in RETIRED:
        return RETIRED[notification_type]
    raise UndeclaredNotificationType(
        f"{notification_type!r} has no entry in notification_spec.SPEC "
        f"(ADR-487 D1). Declare its severity, channels, label, tone and icon. "
        f"A notification with no declared severity cannot be routed, and "
        f"defaulting it to INFO is how an injury alert becomes a grey card."
    )


def is_raisable(notification_type: str) -> bool:
    """False for a retired type — readable, but no longer written."""
    return notification_type in SPEC
