import logging
from datetime import date, datetime, timezone
from typing import Dict, List
from sqlalchemy.orm import Session
from app.models.training import TrainingRecord, TrainingTask, TrainingCurriculum
from app.models.employee import Employee
from app.models.trainer_continuation_request import TrainerContinuationRequest
from app.services.constants import DEBT_ESCALATION_THRESHOLD

logger = logging.getLogger(__name__)

# Phases 1–3 are curriculum phases. Phase 4 is observation (auto-generated).
# Phase 5 is remediation (generated by score_phase4 on fail). Never injected here.
MAX_CURRICULUM_PHASE = 4


def inject_curriculum(db: Session, target_date: date, assigned_crews: Dict[str, List[Dict]]) -> None:
    """
    Hook called at dispatch publish time to auto-generate daily training records
    for all trainees assigned today.

    Phase advancement logic (ADR-046):
    - A phase advances ONLY if the previous record's phase_closed = True.
    - If phase_closed = False, the trainee stays in the same phase.
    - Missed days do not incur debt or penalties — phases only move on days
      the DA is physically dispatched and present.
    - Phase 4 tasks are auto-generated from all mandatory Phase 1–3 curriculum
      items as demonstration tasks, not from a static Phase 4 curriculum.
    - Phase 5 (remediation) records are never injected here; score_phase4 creates them.
    """
    # 1. Identify all trainees and their paired trainer from today's crews
    trainees_in_crews = []
    for truck_id, crew in assigned_crews.items():
        trainer_id = None
        for member in crew:
            if member["role"] == "trainer":
                trainer_id = member["id"]
                break
        for member in crew:
            if member["role"] == "trainee":
                trainees_in_crews.append((member["id"], trainer_id))

    logger.info("inject_curriculum: date=%s trainees=%d", target_date, len(trainees_in_crews))
    if not trainees_in_crews:
        logger.debug("inject_curriculum: no trainees in crews for date=%s — skipping", target_date)
        return

    # 2. Lock past records that are still open (past date, not yet locked)
    unlocked_past = db.query(TrainingRecord).filter(
        TrainingRecord.record_date < target_date,
        TrainingRecord.is_locked == False,
    ).all()
    for rec in unlocked_past:
        rec.is_locked = True
    if unlocked_past:
        db.flush()

    # 3. Fetch full curriculum, grouped by phase
    curriculum = db.query(TrainingCurriculum).order_by(TrainingCurriculum.day_number).all()
    curriculum_by_phase: Dict[int, List[TrainingCurriculum]] = {}
    for item in curriculum:
        curriculum_by_phase.setdefault(item.day_number, []).append(item)

    # Mandatory Phase 1–3 items for Phase 4 observation generation
    mandatory_phases_1_3 = [
        item for item in curriculum
        if item.day_number in (1, 2, 3) and item.is_mandatory
    ]

    for trainee_id, trainer_id in trainees_in_crews:
        # --- Continuation request resolution ---
        active_request = db.query(TrainerContinuationRequest).filter(
            TrainerContinuationRequest.trainee_id == trainee_id,
            TrainerContinuationRequest.status == "accepted",
        ).first()

        if active_request:
            requested_trainer_id = active_request.trainer_id
            trainer_available = any(
                any(m["id"] == requested_trainer_id and m["role"] == "trainer" for m in crew)
                for crew in assigned_crews.values()
            )
            if trainer_available:
                trainer_id = requested_trainer_id
            active_request.status = "nullified"
            active_request.resolved_at = datetime.now(timezone.utc)

        # Auto-expire still-pending requests
        pending_request = db.query(TrainerContinuationRequest).filter(
            TrainerContinuationRequest.trainee_id == trainee_id,
            TrainerContinuationRequest.status == "pending",
        ).first()
        if pending_request:
            pending_request.status = "nullified"
            pending_request.resolved_at = datetime.now(timezone.utc)

        db.flush()

        # --- If record already exists for today, just update trainer ---
        existing_record = db.query(TrainingRecord).filter(
            TrainingRecord.trainee_id == trainee_id,
            TrainingRecord.record_date == target_date,
        ).first()

        if existing_record:
            existing_record.trainer_id = trainer_id
            continue

        # --- Determine current phase ---
        prev_records = db.query(TrainingRecord).filter(
            TrainingRecord.trainee_id == trainee_id,
            TrainingRecord.record_date < target_date,
        ).order_by(TrainingRecord.record_date.desc()).all()

        if not prev_records:
            # First ever dispatch day for this trainee
            current_phase = 1
        else:
            last_record = prev_records[0]

            if last_record.current_day_number >= MAX_CURRICULUM_PHASE and last_record.phase_closed:
                # DA completed Phase 4 and passed — training complete, no new record needed.
                # (If Phase 4 failed, score_phase4 already generated a Phase 5 remediation record.)
                continue

            if last_record.phase_closed:
                # Phase was closed — advance to the next phase
                current_phase = last_record.current_day_number + 1
            else:
                # Phase was not closed — DA stays in the same phase
                current_phase = last_record.current_day_number

        logger.info("inject_curriculum: creating phase=%d record for trainee=%s trainer=%s date=%s", current_phase, trainee_id, trainer_id, target_date)
        # --- Create the new record ---
        new_record = TrainingRecord(
            trainee_id=trainee_id,
            trainer_id=trainer_id,
            record_date=target_date,
            current_day_number=current_phase,
            phase_closed=False,
            extended=False,
        )
        db.add(new_record)
        db.flush()

        # --- Roll over debt from previous uncompleted mandatory coverage tasks ---
        debt_tasks = []
        if prev_records:
            prev_record_ids = [r.id for r in prev_records]
            uncompleted_mandatory = db.query(TrainingTask).filter(
                TrainingTask.training_record_id.in_(prev_record_ids),
                TrainingTask.is_mandatory == True,
                TrainingTask.is_completed == False,
                TrainingTask.record_type == "coverage",
            ).all()

            # Deduplicate by topic title
            seen_titles = set()
            for task in uncompleted_mandatory:
                if task.topic_title not in seen_titles:
                    seen_titles.add(task.topic_title)
                    debt_tasks.append(task)

        for dt in debt_tasks:
            new_debt_age = (dt.debt_age or 0) + 1
            debt_task = TrainingTask(
                training_record_id=new_record.id,
                topic_title=dt.topic_title,
                description=dt.description,
                is_mandatory=True,
                is_training_debt=True,
                record_type="coverage",
                debt_age=new_debt_age,
                is_escalated=new_debt_age >= DEBT_ESCALATION_THRESHOLD,
            )
            db.add(debt_task)

        # --- Add tasks for current phase ---
        if current_phase == 4:
            # Phase 4: generate observation tasks from all mandatory Phase 1–3 curriculum items
            for item in mandatory_phases_1_3:
                # Skip if already in debt (debt items are coverage tasks; observation tasks are separate)
                new_task = TrainingTask(
                    training_record_id=new_record.id,
                    topic_title=item.topic_title,
                    description=item.description,
                    record_type="demonstration",
                    is_mandatory=True,
                    is_training_debt=False,
                )
                db.add(new_task)
        else:
            # Phases 1–3: add coverage tasks from curriculum
            phase_items = curriculum_by_phase.get(current_phase, [])
            debt_titles = {dt.topic_title for dt in debt_tasks}
            for ct in phase_items:
                if ct.topic_title in debt_titles:
                    continue  # already added as debt task, don't duplicate
                new_task = TrainingTask(
                    training_record_id=new_record.id,
                    topic_title=ct.topic_title,
                    description=ct.description,
                    record_type="coverage",
                    is_mandatory=ct.is_mandatory,
                    is_training_debt=False,
                )
                db.add(new_task)

    db.commit()
