"""Generate the logo/favicon set from design/palette.json (plan 0.5).

    python design/build_brand_assets.py            # write
    python design/build_brand_assets.py --check    # verify in sync (CI)

## Why generated

The repo carried TWO conflicting identities (plan §2.7):

  frontend/src/assets/*.svg      the real mark, on the OLD indigo/amber
  frontend/public/favicon.svg    an unrelated purple lightning bolt — a
                                 leftover template, and the one actually
                                 wired into the browser tab
  frontend/public/icons.svg      purple/cyan, referenced by nothing

Hand-maintained SVGs drift from the palette exactly the way the two theme files
did. Generating them means "change the palette, re-run, done" instead of
editing six files and missing one.

## Interim, not final

The real mark is being commissioned from a human designer. This keeps the
CURRENT mark's geometry (three dots feeding a rounded square, one line out —
an intake/sort/dispatch flow) and only re-colours it onto the settled palette,
so nothing in the UI contradicts the tokens while that work happens.

When the designer delivers, replace the geometry in this file; the colour
plumbing stays.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parent
SPEC = ROOT / "palette.json"
ASSETS = REPO / "frontend" / "src" / "assets"
PUBLIC = REPO / "frontend" / "public"

BANNER = "AUTO-GENERATED by design/build_brand_assets.py from design/palette.json"


def hsl(spec: dict, theme: str, token: str) -> str:
    h, s, l = spec[theme][token]["hsl"]
    return f"hsl({h} {s}% {l}%)"


def _mark_paths(stroke: str, block: str, dot: str) -> str:
    """The AsheFlow mark: three inputs converge into a block, one output.

    Geometry preserved from the existing mark — only the colours change.
    """
    return f"""  <line x1="4" y1="13" x2="17" y2="22" stroke="{stroke}" stroke-width="2.6" stroke-linecap="round"/>
  <line x1="4" y1="24" x2="17" y2="24" stroke="{stroke}" stroke-width="2.6" stroke-linecap="round"/>
  <line x1="4" y1="35" x2="17" y2="26" stroke="{stroke}" stroke-width="2.6" stroke-linecap="round"/>
  <circle cx="5" cy="13" r="2.2" fill="{stroke}"/>
  <circle cx="5" cy="24" r="2.2" fill="{stroke}"/>
  <circle cx="5" cy="35" r="2.2" fill="{stroke}"/>
  <rect x="16" y="16" width="16" height="16" rx="3.5" fill="{block}"/>
  <rect x="20.5" y="20.5" width="7" height="7" rx="1.2" fill="{dot}" opacity="0.95"/>
  <line x1="32" y1="24" x2="41" y2="24" stroke="{block}" stroke-width="2.6" stroke-linecap="round"/>"""


def build(spec: dict) -> dict[pathlib.Path, str]:
    # Light surfaces: navy block, amber inputs. Dark surfaces: the lifted
    # variants, because navy on near-black is unreadable.
    navy_l, gold_l = hsl(spec, "light", "primary"), hsl(spec, "light", "gold")
    navy_d, gold_d = hsl(spec, "dark", "primary"), hsl(spec, "dark", "gold")
    fg_l, fg_d = hsl(spec, "light", "foreground"), hsl(spec, "dark", "foreground")

    out: dict[pathlib.Path, str] = {}

    def svg(view: str, body: str) -> str:
        return (f'<!-- {BANNER} -->\n'
                f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" fill="none" '
                f'role="img" aria-label="AsheFlow">\n{body}\n</svg>\n')

    out[ASSETS / "logo-mark.svg"] = svg("0 0 48 48", _mark_paths(gold_l, navy_l, "white"))
    out[ASSETS / "logo-mark-light.svg"] = svg("0 0 48 48", _mark_paths(gold_d, navy_d, fg_d))

    # Favicon: a filled tile so the mark reads at 16px against any tab colour.
    out[ASSETS / "favicon.svg"] = svg(
        "0 0 48 48",
        f'  <rect width="48" height="48" rx="10" fill="{navy_l}"/>\n'
        + _mark_paths(gold_d, "white", navy_l).replace(
            'fill="white" opacity="0.95"', f'fill="{navy_l}" opacity="0.95"')
    )
    # The browser tab currently points at public/ — keep both identical rather
    # than leaving a second, divergent file (that is how the bolt survived).
    out[PUBLIC / "favicon.svg"] = out[ASSETS / "favicon.svg"]

    wordmark = ('  <text x="0" y="34" font-family="Sora, Inter, system-ui, sans-serif" '
                'font-size="30" font-weight="700" fill="{fill}">AsheFlow</text>')
    out[ASSETS / "logo-wordmark.svg"] = svg("0 0 190 48", wordmark.format(fill=fg_l))

    lock = ('{mark}\n  <text x="60" y="33" font-family="Sora, Inter, system-ui, sans-serif" '
            'font-size="27" font-weight="700" fill="{fill}">AsheFlow</text>')
    out[ASSETS / "logo-full.svg"] = svg(
        "0 0 245 48", lock.format(mark=_mark_paths(gold_l, navy_l, "white"), fill=fg_l))
    out[ASSETS / "logo-full-light.svg"] = svg(
        "0 0 245 48", lock.format(mark=_mark_paths(gold_d, navy_d, fg_d), fill=fg_d))
    return out


def main(check_only: bool = False) -> int:
    spec = json.loads(SPEC.read_text())
    outputs = build(spec)

    if check_only:
        stale = [p.relative_to(REPO) for p, c in outputs.items()
                 if not p.exists() or p.read_text() != c]
        if stale:
            print("\nBRAND ASSETS ARE STALE:\n")
            for p in stale:
                print(f"  {p}")
            print("\nRun `python design/build_brand_assets.py` and commit the result.")
            return 1
        print(f"OK — {len(outputs)} brand assets match the palette")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"  wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(check_only="--check" in sys.argv))
