"""Generate web CSS vars and mobile TS colours from design/palette.json.

    python design/build_tokens.py            # write both platforms
    python design/build_tokens.py --check    # verify in sync (CI); exit 1 if not

Writes:
    frontend/src/generated-tokens.css     imported by index.css
    mobile/src/theme/generated-colors.ts  imported by theme/index.ts

## Why generate instead of hand-maintaining two files

They drifted: web primary was #3C64DD, mobile #4F6BF4 — the same intent, two
values, because nothing tied them together (plan §2.7). Generation makes that
class of drift impossible rather than merely discouraged.

Contrast is verified BEFORE anything is written, so a failing palette cannot
reach either platform. `--check` regenerates in memory and diffs, which is what
CI runs: it catches someone hand-editing a generated file as readily as it
catches a stale build.

## Scope

This emits COLOUR only. Spacing, radius, typography and motion stay hand-owned
in each platform's theme file — they are not the thing that drifted, and pulling
them in would make this generator the owner of layout decisions it has no
opinion about.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parent
SPEC = ROOT / "palette.json"

WEB_OUT = REPO / "frontend" / "src" / "generated-tokens.css"
MOBILE_OUT = REPO / "mobile" / "src" / "theme" / "generated-colors.ts"

BANNER = "AUTO-GENERATED by design/build_tokens.py from design/palette.json"


def _camel_to_kebab(name: str) -> str:
    out = []
    for ch in name:
        if ch.isupper():
            out.append("-")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)


def _tokens(theme: dict) -> list[tuple[str, tuple[float, float, float]]]:
    return [
        (k, tuple(v["hsl"]))
        for k, v in theme.items()
        if isinstance(v, dict) and "hsl" in v
    ]


def build_web(spec: dict) -> str:
    lines = [
        "/* " + BANNER + " —",
        " * do not edit. Change the palette and re-run the generator.",
        " *",
        " * HSL triples (not hex) because Tailwind composes them as",
        " * hsl(var(--token) / <alpha-value>) for opacity variants.",
        " */",
        "",
        "@layer base {",
        "  :root {",
    ]
    for name, (h, s, l) in _tokens(spec["light"]):
        lines.append(f"    --{_camel_to_kebab(name)}: {h} {s}% {l}%;")
    lines += ["  }", "", "  .dark {"]
    for name, (h, s, l) in _tokens(spec["dark"]):
        lines.append(f"    --{_camel_to_kebab(name)}: {h} {s}% {l}%;")
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def build_mobile(spec: dict) -> str:
    from check_contrast import hsl_to_hex

    light = _tokens(spec["light"])
    dark = _tokens(spec["dark"])
    dark_names = {n for n, _ in dark}

    missing = [n for n, _ in light if n not in dark_names]
    if missing:
        raise SystemExit(
            f"palette.json: dark theme is missing tokens present in light: {missing}\n"
            f"Both themes must declare the same token set, or ThemeColors cannot be "
            f"one type."
        )

    width = max(len(n) for n, _ in light) + 1
    lines = [
        "// " + BANNER + " —",
        "// do not edit. Change the palette and re-run the generator.",
        "//",
        "// Hex (not HSL) because React Native's StyleSheet takes colour strings",
        "// directly and gains nothing from a composable triple.",
        "",
        "export type GeneratedColors = {",
    ]
    for name, _ in light:
        lines.append(f"  {name}{':':<{width - len(name)}} string;")
    lines += ["};", "", "export const generatedLight: GeneratedColors = {"]
    for name, hsl in light:
        lines.append(f"  {(name + ':'):<{width}} '{hsl_to_hex(*hsl)}',")
    lines += ["};", "", "export const generatedDark: GeneratedColors = {"]
    for name, hsl in dark:
        lines.append(f"  {(name + ':'):<{width}} '{hsl_to_hex(*hsl)}',")
    lines += ["};", ""]
    return "\n".join(lines)


def main(check_only: bool = False) -> int:
    sys.path.insert(0, str(ROOT))
    from check_contrast import check

    # A palette that fails contrast must never reach a platform.
    if check() != 0:
        print("\nRefusing to generate tokens from a failing palette.")
        return 1

    spec = json.loads(SPEC.read_text())
    outputs = {WEB_OUT: build_web(spec), MOBILE_OUT: build_mobile(spec)}

    if check_only:
        stale = []
        for path, content in outputs.items():
            current = path.read_text() if path.exists() else None
            if current != content:
                stale.append(path.relative_to(REPO))
        if stale:
            print("\nGENERATED TOKENS ARE STALE:\n")
            for p in stale:
                print(f"  {p}")
            print(
                "\nRun `python design/build_tokens.py` and commit the result.\n"
                "If you hand-edited one of these, don't — edit design/palette.json."
            )
            return 1
        print("OK — generated tokens match the palette")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"  wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(check_only="--check" in sys.argv))
