"""add_incidents_table

Revision ID: 0013944a1052
Revises: 366a22849cdd
Create Date: 2026-04-10 23:56:53.393771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013944a1052'
down_revision: Union[str, Sequence[str], None] = '366a22849cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('packages_tba', sa.Integer(), nullable=True),
    sa.Column('incident_location', sa.Text(), nullable=True),
    sa.Column('witness_name', sa.Text(), nullable=True),
    sa.Column('body_part_affected', sa.Text(), nullable=True),
    sa.Column('medical_attention_required', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_date'), 'incidents', ['date'], unique=False)
    op.create_index(op.f('ix_incidents_reporter_id'), 'incidents', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_reporter_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_date'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
