"""fix_walker_rating_stars_integer

Revision ID: 366a22849cdd
Revises: b3cfc071a7ff
Create Date: 2026-04-10 23:26:08.755029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366a22849cdd'
down_revision: Union[str, Sequence[str], None] = 'b3cfc071a7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walker_ratings', 'stars',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='stars::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walker_ratings', 'stars',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
