"""add_driver_id_to_incidents

Revision ID: 3f1b3e4336bc
Revises: 0013944a1052
Create Date: 2026-04-11 00:20:45.634855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1b3e4336bc'
down_revision: Union[str, Sequence[str], None] = '0013944a1052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'employees', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'driver_id')
    # ### end Alembic commands ###
