"""add_priority_to_continuation_requests

Revision ID: 3f487497f021
Revises: fc431d5d5452
Create Date: 2026-04-10 12:58:09.152679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f487497f021'
down_revision: Union[str, Sequence[str], None] = 'fc431d5d5452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_continuation_requests', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('trainer_continuation_requests', 'priority')
    # ### end Alembic commands ###
