"""Initial schema

Revision ID: 538ddc3b76d1
Revises: 
Create Date: 2026-04-08 11:05:47.214404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538ddc3b76d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_discord_id'), 'employees', ['discord_id'], unique=True)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_role'), 'employees', ['role'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_is_active'), 'trucks', ['is_active'], unique=False)
    op.create_index(op.f('ix_trucks_name'), 'trucks', ['name'], unique=True)
    op.create_table('employee_off_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.CheckConstraint("day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')", name='ck_employee_off_days_day_of_week'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'day_of_week', name='uq_emp_off_day')
    )
    op.create_index(op.f('ix_employee_off_days_day_of_week'), 'employee_off_days', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_employee_off_days_employee_id'), 'employee_off_days', ['employee_id'], unique=False)
    op.create_table('employee_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('target_employee_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=10), nullable=False),
    sa.CheckConstraint("relationship_type IN ('ban', 'fav')", name='ck_employee_relationships_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'target_employee_id', 'relationship_type', name='uq_emp_relationship')
    )
    op.create_index(op.f('ix_employee_relationships_employee_id'), 'employee_relationships', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_relationships_target_employee_id'), 'employee_relationships', ['target_employee_id'], unique=False)
    op.create_table('truck_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed')", name='ck_truck_assignments_status'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_id', 'date', name='uq_truck_assignment_date')
    )
    op.create_index(op.f('ix_truck_assignments_date'), 'truck_assignments', ['date'], unique=False)
    op.create_index(op.f('ix_truck_assignments_truck_id'), 'truck_assignments', ['truck_id'], unique=False)
    op.create_table('assignment_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.CheckConstraint("role IN ('driver', 'trainer', 'walker')", name='ck_assignment_members_role'),
    sa.ForeignKeyConstraint(['assignment_id'], ['truck_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'employee_id', name='uq_assignment_member')
    )
    op.create_index(op.f('ix_assignment_members_assignment_id'), 'assignment_members', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_members_employee_id'), 'assignment_members', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_members_employee_id'), table_name='assignment_members')
    op.drop_index(op.f('ix_assignment_members_assignment_id'), table_name='assignment_members')
    op.drop_table('assignment_members')
    op.drop_index(op.f('ix_truck_assignments_truck_id'), table_name='truck_assignments')
    op.drop_index(op.f('ix_truck_assignments_date'), table_name='truck_assignments')
    op.drop_table('truck_assignments')
    op.drop_index(op.f('ix_employee_relationships_target_employee_id'), table_name='employee_relationships')
    op.drop_index(op.f('ix_employee_relationships_employee_id'), table_name='employee_relationships')
    op.drop_table('employee_relationships')
    op.drop_index(op.f('ix_employee_off_days_employee_id'), table_name='employee_off_days')
    op.drop_index(op.f('ix_employee_off_days_day_of_week'), table_name='employee_off_days')
    op.drop_table('employee_off_days')
    op.drop_index(op.f('ix_trucks_name'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_is_active'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_employees_role'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_discord_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
