"""add_email_cognito_sub_to_employees

Revision ID: 6f6843738bc0
Revises: 0a1af9262ce6
Create Date: 2026-04-12 00:27:21.472387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6843738bc0'
down_revision: Union[str, Sequence[str], None] = '0a1af9262ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('cognito_sub', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_employees_cognito_sub'), 'employees', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_cognito_sub'), table_name='employees')
    op.drop_column('employees', 'cognito_sub')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
