"""add_field_ops_tables

Revision ID: 8523668a4665
Revises: 7956f5c3c2af
Create Date: 2026-04-10 01:17:30.725712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8523668a4665'
down_revision: Union[str, Sequence[str], None] = '7956f5c3c2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_date'), 'check_ins', ['date'], unique=False)
    op.create_index(op.f('ix_check_ins_employee_id'), 'check_ins', ['employee_id'], unique=False)
    op.create_table('departures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('itinerary_photo_url', sa.Text(), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departures_date'), 'departures', ['date'], unique=False)
    op.create_index(op.f('ix_departures_employee_id'), 'departures', ['employee_id'], unique=False)
    op.create_table('walker_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('walker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stars', sa.String(length=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['walker_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walker_ratings_date'), 'walker_ratings', ['date'], unique=False)
    op.create_index(op.f('ix_walker_ratings_driver_id'), 'walker_ratings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_walker_ratings_walker_id'), 'walker_ratings', ['walker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walker_ratings_walker_id'), table_name='walker_ratings')
    op.drop_index(op.f('ix_walker_ratings_driver_id'), table_name='walker_ratings')
    op.drop_index(op.f('ix_walker_ratings_date'), table_name='walker_ratings')
    op.drop_table('walker_ratings')
    op.drop_index(op.f('ix_departures_employee_id'), table_name='departures')
    op.drop_index(op.f('ix_departures_date'), table_name='departures')
    op.drop_table('departures')
    op.drop_index(op.f('ix_check_ins_employee_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_date'), table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###
