"""add_returned_at_to_departures

Revision ID: aa7f771104eb
Revises: 3f1b3e4336bc
Create Date: 2026-04-11 00:26:32.268290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7f771104eb'
down_revision: Union[str, Sequence[str], None] = '3f1b3e4336bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departures', sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departures', 'returned_at')
    # ### end Alembic commands ###
