"""add_assignment_change_requests_table

Revision ID: b3cfc071a7ff
Revises: 3f487497f021
Create Date: 2026-04-10 15:11:50.845799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cfc071a7ff'
down_revision: Union[str, Sequence[str], None] = '3f487497f021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_change_requests_employee_id'), 'assignment_change_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assignment_change_requests_requested_date'), 'assignment_change_requests', ['requested_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_change_requests_requested_date'), table_name='assignment_change_requests')
    op.drop_index(op.f('ix_assignment_change_requests_employee_id'), table_name='assignment_change_requests')
    op.drop_table('assignment_change_requests')
    # ### end Alembic commands ###
