"""Add training models

Revision ID: cec73d660c0a
Revises: 8c0335d1ffdc
Create Date: 2026-04-09 07:52:18.227080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec73d660c0a'
down_revision: Union[str, Sequence[str], None] = '8c0335d1ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_curriculums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_curriculums_day_number'), 'training_curriculums', ['day_number'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('current_day_number', sa.Integer(), nullable=False),
    sa.Column('trainer_comments', sa.Text(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_record_date'), 'training_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_training_records_trainee_id'), 'training_records', ['trainee_id'], unique=False)
    op.create_index(op.f('ix_training_records_trainer_id'), 'training_records', ['trainer_id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_record_id', sa.UUID(), nullable=False),
    sa.Column('topic_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_training_debt', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_record_id'], ['training_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_tasks_training_record_id'), 'training_tasks', ['training_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_tasks_training_record_id'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_training_records_trainer_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_trainee_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_record_date'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_training_curriculums_day_number'), table_name='training_curriculums')
    op.drop_table('training_curriculums')
    # ### end Alembic commands ###
