"""Add status to employee_off_days

Revision ID: d1a1338178ba
Revises: 538ddc3b76d1
Create Date: 2026-04-08 23:03:02.581633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a1338178ba'
down_revision: Union[str, Sequence[str], None] = '538ddc3b76d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_off_days', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.create_index(op.f('ix_employee_off_days_status'), 'employee_off_days', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_off_days_status'), table_name='employee_off_days')
    op.drop_column('employee_off_days', 'status')
    # ### end Alembic commands ###
