"""add_schedule_change_requests_table

Revision ID: dd69d9df05d9
Revises: e7d2130af5b1
Create Date: 2026-04-11 02:30:21.235381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd69d9df05d9'
down_revision: Union[str, Sequence[str], None] = 'e7d2130af5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('days_to_add', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('days_to_drop', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('proposed_schedule', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_change_requests_employee_id'), 'schedule_change_requests', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_change_requests_employee_id'), table_name='schedule_change_requests')
    op.drop_table('schedule_change_requests')
    # ### end Alembic commands ###
