"""Add time_off_requests table

Revision ID: f996344de217
Revises: d1a1338178ba
Create Date: 2026-04-09 00:11:26.834417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f996344de217'
down_revision: Union[str, Sequence[str], None] = 'd1a1338178ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='valid_time_off_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_id'), 'time_off_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_off_requests_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    # ### end Alembic commands ###
