"""add_trainer_continuation_requests

Revision ID: fc431d5d5452
Revises: a79c6156f489
Create Date: 2026-04-10 12:02:24.241790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc431d5d5452'
down_revision: Union[str, Sequence[str], None] = 'a79c6156f489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_continuation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_continuation_requests_trainee_id'), 'trainer_continuation_requests', ['trainee_id'], unique=False)
    op.create_index(op.f('ix_trainer_continuation_requests_trainer_id'), 'trainer_continuation_requests', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_continuation_requests_trainer_id'), table_name='trainer_continuation_requests')
    op.drop_index(op.f('ix_trainer_continuation_requests_trainee_id'), table_name='trainer_continuation_requests')
    op.drop_table('trainer_continuation_requests')
    # ### end Alembic commands ###
