import React, { useEffect, useState } from 'react';
import axiosClient from '../../api/axiosClient';
import { useAuth } from '../../contexts/AuthContext';
import { Users, Loader2 } from 'lucide-react';
import TaskChecklist from '../../components/TrainerDashboard/TaskChecklist';
import ManagerComments from '../../components/TrainerDashboard/ManagerComments';

function getLocalYMD() {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export default function TrainerDashboard() {
  const { user } = useAuth();
  const [traineeId, setTraineeId] = useState<string | null>(null);
  const [traineeName, setTraineeName] = useState<string>('');
  const [trainingRecords, setTrainingRecords] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchTrainee = async () => {
      try {
        if (!user) return;
        const today = getLocalYMD();
        
        // Find if the trainer has a truck assignment today
        const scheduleRes = await axiosClient.get(`/schedule/${user.username || (user as any).id}?start_date=${today}&end_date=${today}`);
        const todaySchedule = scheduleRes.data[0];
        
        if (todaySchedule && todaySchedule.status === 'Assigned' && todaySchedule.crew) {
          // Look for a trainee in the crew
          const trainee = todaySchedule.crew.find((c: any) => c.role.toLowerCase() === 'trainee');
          if (trainee) {
            setTraineeId(trainee.id);
            setTraineeName(trainee.name);
          }
        }
      } catch (error) {
        console.error('Failed to fetch schedule for Trainer Dashboard:', error);
      }
      setIsLoading(false);
    };

    fetchTrainee();
  }, [user]);

  useEffect(() => {
    if (!traineeId) return;

    const fetchHistory = async () => {
      try {
        const res = await axiosClient.get(`/training/trainee/${traineeId}`);
        setTrainingRecords(res.data);
      } catch (error) {
        console.error('Failed to fetch training records:', error);
      }
    };
    fetchHistory();
  }, [traineeId]);

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center py-20 opacity-50">
        <Loader2 className="w-8 h-8 text-primary animate-spin mb-4" />
        <p className="text-sm font-medium">Checking today's assignments...</p>
      </div>
    );
  }

  if (!traineeId) {
    return (
      <div className="space-y-4 animate-slide-up">
         <h1 className="page-title">Trainer Dashboard</h1>
         <div className="card text-center py-16 flex flex-col items-center justify-center">
            <div className="w-16 h-16 rounded-full bg-accent/50 flex items-center justify-center mb-4">
              <Users className="text-subtle w-8 h-8" />
            </div>
            <h2 className="text-xl font-semibold mb-2">No Trainee Assigned</h2>
            <p className="text-subtle max-w-sm mx-auto">You do not have a trainee currently assigned to your truck for today's dispatch runs.</p>
         </div>
      </div>
    );
  }

  const sortedRecords = [...trainingRecords].sort((a, b) => new Date(b.record_date).getTime() - new Date(a.record_date).getTime());
  const todayRecord = sortedRecords.find(r => r.record_date === getLocalYMD());
  const pastRecords = sortedRecords.filter(r => r.record_date !== getLocalYMD());

  return (
    <div className="space-y-6 animate-slide-up">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="page-title">Training: {traineeName}</h1>
          <p className="text-subtle mt-1 flex items-center gap-2">
            <span className="inline-block w-2 flex-none rounded-full h-2 bg-success"></span>
            Lifecycle Day {todayRecord?.current_day_number || '...'}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
           {todayRecord ? (
             <TaskChecklist 
               record={todayRecord} 
               isReadOnly={todayRecord.is_locked} 
             />
           ) : (
             <div className="card text-center text-subtle py-12">
                <p className="text-lg font-semibold mb-2 text-foreground">Waiting for Dispatch</p>
                <p className="text-sm px-2">Today's official training record hasn't been generated by the system yet. This usually occurs when the daily dispatch map is generated.</p>
             </div>
           )}
           
           <div className="card">
              <h2 className="text-lg font-semibold mb-4">Historical Log</h2>
              {pastRecords.length === 0 ? (
                 <div className="text-center py-6 bg-accent border border-transparent border-dashed rounded-xl">
                    <p className="text-subtle text-sm">No historical records found.<br/>This appears to be their first day.</p>
                 </div>
              ) : (
                <div className="space-y-4">
                  {pastRecords.map(record => (
                    <div key={record.id} className="border border-border rounded-xl p-4 flex flex-col gap-3">
                      <div className="flex justify-between items-center bg-accent/40 rounded-lg p-2.5">
                         <span className="font-semibold text-foreground text-sm">Day {record.current_day_number} &middot; {new Date(record.record_date).toLocaleDateString()}</span>
                         <span className="text-xs px-2 py-0.5 rounded-md bg-foreground/10 text-muted-foreground font-medium">Locked</span>
                      </div>
                      <div className="text-sm space-y-2.5 px-1 py-1">
                        {record.tasks?.map((task: any) => (
                           <div key={task.id} className="flex gap-2.5 items-start">
                              {task.is_completed ? <span className="text-success text-base flex-shrink-0">&check;</span> : <span className="text-danger flex-shrink-0 font-bold">&times;</span>}
                              <span className={task.is_completed ? "text-subtle strike text-balance leading-relaxed line-through" : "text-foreground font-medium leading-relaxed"}>{task.topic_title}</span>
                           </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}
           </div>
        </div>

        <div className="space-y-6">
           <ManagerComments 
             record={todayRecord} 
             traineeId={traineeId}
           />
        </div>
      </div>
    </div>
  );
}